### ISSUE TITLE
Dependancies

### ISSUE THREAD

**Issue by chrhlnd** [couchbaselabs/couchstore#12]
Trying to build it errors out asking for v8? Its not listed on the front page, I'm going down the dependency rabbit hole now.

checking for library containing fabs... none required
checking for pod2man... /usr/bin/pod2man
checking snappy-c.h usability... yes
checking snappy-c.h presence... yes
checking for snappy-c.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for inttypes.h... (cached) yes
checking for libsnappy... yes
checking for icu-config... /opt/couchbase/bin/icu-config
checking for ICU >= 3.4.1... yes
checking ICU_CFLAGS... -O3 -ggdb3 -Wall -ansi -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long
checking ICU_CXXFLAGS... -O3 -ggdb3 -W -Wall -ansi -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long
checking ICU_LIBS...  -lpthread -ldl -lm   -L/opt/couchbase/lib -licui18n -licuuc -licudata  -lpthread -ldl -lm
checking v8.h usability... no
checking v8.h presence... no
checking for v8.h... no
configure: error: Could not find the V8 JavaScript engine library.

**Comment by baijuviswam** [comment]
i'm also stuck with this
